"""Extract every gated question from lessons/*.html into reference/question-bank.js.

Run after adding or editing lesson questions:  python3 tools/build_question_bank.py
The bank is a <script>-loadable JS file (not JSON via fetch) so it works from file://.
Sections come from the headings in index.html, in order, so the review page can run
cumulative end-of-section exams.
"""
import glob, html, json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def sections_from_index():
    s = open(os.path.join(ROOT, 'index.html')).read()
    out, phase, sub = [], None, None
    for m in re.finditer(r'<h2>(.*?)</h2>|<h3[^>]*>(.*?)</h3>|href="lessons/(0\d+[^"]*\.html)"', s, re.S):
        if m.group(1):
            phase, sub = html.unescape(re.sub('<[^>]+>', '', m.group(1))).strip(), None
        elif m.group(2):
            sub = html.unescape(re.sub('<[^>]+>', '', m.group(2))).replace('(added)', '').strip().title()
        else:
            name = phase + (' — ' + sub if sub else '')
            if not out or out[-1]['name'] != name:
                out.append({'name': name, 'phase': phase, 'lessons': []})
            if m.group(3) not in out[-1]['lessons']:
                out[-1]['lessons'].append(m.group(3))
    return out

def lesson_questions(path):
    s = open(path).read()
    title = html.unescape(re.sub('<[^>]+>', '', re.search(r'<h1>(.*?)</h1>', s, re.S).group(1))).strip()
    qs = []
    chunks = [(m.group(1), m.group(2)) for m in re.finditer(r'<section class="chunk" id="([^"]+)"(.*?)</section>', s, re.S)]
    if not chunks:  # ungated pages (the prerequisite diagnostic) are one block
        chunks = [('diagnostic', s)]
    for chunk_id, body in chunks:
        for qm in re.finditer(r'<div class="q"([^>]*)>(.*?)\n\s*</div>', body, re.S):
            attrs, inner = qm.group(1), qm.group(2)
            concept = re.search(r'data-concept="([^"]+)"', attrs)
            correct = re.search(r'data-correct="([a-d])"', attrs)
            if not concept or not correct:
                continue
            opts = re.findall(r'<button class="opt">(.*?)</button>', inner, re.S)
            get = lambda cls: (re.search(r'<p class="%s">(.*?)</p>' % cls, inner, re.S) or [None, ''])[1]
            qs.append({
                'id': concept.group(1),
                'lesson': os.path.basename(path),
                'chunk': chunk_id,
                'final': chunk_id == 'chunk-final',
                'intuition': 'data-type="intuition"' in attrs,
                'stem': re.sub(r'^\d+\.\s*', '', get('stem').strip()),
                'opts': [o.strip() for o in opts],
                'correct': 'abcd'.index(correct.group(1)),
                'fb': get('fb').strip(),
                'hint': get('hint').strip(),
            })
    return title, qs

def main():
    lessons, questions = {}, []
    for path in sorted(glob.glob(os.path.join(ROOT, 'lessons', '0*.html'))):
        title, qs = lesson_questions(path)
        lessons[os.path.basename(path)] = title
        questions += qs
    bank = {'sections': sections_from_index(), 'lessons': lessons, 'questions': questions}
    out = os.path.join(ROOT, 'reference', 'question-bank.js')
    with open(out, 'w') as f:
        f.write('// Generated by tools/build_question_bank.py — do not edit by hand.\n')
        f.write('window.SD_BANK = ' + json.dumps(bank, ensure_ascii=False, separators=(',', ':')) + ';\n')
    print(f"{len(questions)} questions from {len(lessons)} lessons, {len(bank['sections'])} sections -> {out}")

if __name__ == '__main__':
    main()
